services:
  #####################
  # Olymipics dataset #
  #####################
  server-olympics:
    profiles:
      - olympics
    build:
      context: ./docker/
      dockerfile: ./server.Dockerfile
    user: 1000:1000
    stop_grace_period: 0s
    ports:
      - "7001:7001"
    env_file:
      - olympics.env

  ui-olympics:
    profiles:
      - olympics
    build:
      context: ./docker/
      dockerfile: ./ui.Dockerfile
    stop_grace_period: 0s
    ports:
      - "7002:7002"
    depends_on:
      - server-olympics
    env_file:
      - olympics.env

  ###################
  # Local data file #
  ###################
  server-local:
    profiles:
      - local
    build:
      context: ./docker/
      dockerfile: ./server.Dockerfile
    user: 1000:1000
    stop_grace_period: 0s
    ports:
      - "7001:7001"
    env_file:
      - local.env
    volumes:
      - ./docker/server/data.nt:/home/qlever/data/data.nt

  ui-local:
    profiles:
      - local
    build:
      context: ./docker/
      dockerfile: ./ui.Dockerfile
    stop_grace_period: 0s
    ports:
      - "7002:7002"
    depends_on:
      - server-local
    env_file:
      - local.env
