services:
  #####################
  # Olymipics dataset #
  #####################
  server-olympics:
    profiles:
      - olympics
    image: ghcr.io/zazukoians/qlever-server:latest
    build:
      context: ./docker/
      dockerfile: ./server.Dockerfile
    user: "65534:0"
    stop_grace_period: 0s
    ports:
      - "7001:7001"
    env_file:
      - olympics.env

  ui-init-olympics:
    profiles:
      - olympics
    image: docker.io/library/busybox
    command: ["sh", "-c", "chown -R 65534:0 /data"]
    stop_grace_period: 0s
    restart: "no"
    volumes:
      - ./volumes/olympics/ui:/data

  ui-olympics:
    profiles:
      - olympics
    image: ghcr.io/zazukoians/qlever-ui:latest
    build:
      context: ./docker/
      dockerfile: ./ui.Dockerfile
    user: "65534:0"
    stop_grace_period: 0s
    ports:
      - "7002:7002"
    depends_on:
      - server-olympics
    env_file:
      - olympics.env
    volumes:
      - ./volumes/olympics/ui:/app/db

  ###################
  # Local data file #
  ###################
  server-local:
    profiles:
      - local
    image: ghcr.io/zazukoians/qlever-server:latest
    build:
      context: ./docker/
      dockerfile: ./server.Dockerfile
    user: "65534:0"
    stop_grace_period: 0s
    ports:
      - "7001:7001"
    environment:
      - FORCE_INDEXING=true
    env_file:
      - local.env
    volumes:
      - ./docker/server/data.nt:/data/data.nt:ro

  ui-init-local:
    profiles:
      - local
    image: docker.io/library/busybox
    command: ["sh", "-c", "chown -R 65534:0 /data"]
    stop_grace_period: 0s
    restart: "no"
    volumes:
      - ./volumes/local/ui:/data

  ui-local:
    profiles:
      - local
    image: ghcr.io/zazukoians/qlever-ui:latest
    build:
      context: ./docker/
      dockerfile: ./ui.Dockerfile
    user: "65534:0"
    stop_grace_period: 0s
    ports:
      - "7002:7002"
    depends_on:
      - server-local
    env_file:
      - local.env
    volumes:
      - ./volumes/local/ui:/app/db

  ######################
  # Petrimaps instance #
  ######################
  qlever-petrimaps:
    profiles:
      - local
      - olympics
    image: docker.io/adfreiburg/qlever-petrimaps:latest
    stop_grace_period: 0s
    restart: unless-stopped
    ports:
      - "7003:9090"
